modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "GNU"

[[mods]]
modId = "immersive_armors"
version = "${version}"
displayName = "Immersive Armor"
authors = "Luke100000"
description = '''
A lot of unique and vanilla-faithful armor sets.
'''
logoFile = "banner.png"

[[dependencies.immersive_armors]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.immersive_armors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
